# Color scheme {{{

background_blur 0

background_opacity 1.0

# Cyberpunk / Retro Terminal (Preto profundo e Verde Neon)
background           #080c0a
foreground           #8fbfa0
cursor               #26e664
cursor_trail_color   #26e664
selection_background #122416
selection_foreground #26e664

# Cores do Terminal
# Black / Grey (O chassi e tons metálicos escuros)
color0  #080c0a
color8  #15301b

# Red (Vermelho de alerta/LEDs de aviso)
color1  #c44d3b
color9  #e06553

# Green (Verde terminal de fósforo/neon Matrix)
color2  #597a61
color10 #26e664

# Yellow / Gold (O Laranja-Âmbar do teclado e lâmpadas)
color3  #b35114
color11 #f07124

# Blue (Tons azulados frios dos reflexos das telas secundárias)
color4  #355e54
color12 #4d8c7c

# Magenta (Tons roxos escuros de interferência)
color5  #613d54
color13 #945d80

# Cyan (Ciano esverdeado/CRT de radar)
color6  #3a6b57
color14 #52967a

# White (Tons claros para contraste de texto)
color7  #8fbfa0
color15 #d7ffd9

# Tab bar {{{
tab_bar_edge bottom
tab_bar_style powerline
active_tab_font_style bold

# --- Cores Estilo Matrix ---
active_tab_foreground   #080c0a
active_tab_background   #00ff66
inactive_tab_foreground #00ff66
inactive_tab_background #0a1f0a
tab_bar_background      #080c0a
# ---------------------------
