#Color scheme {{{

background_blur 0
background_opacity 1.0

# Noir City (Monochrome Night Sky)
background           #0f0f0f
foreground           #d1d1d1
cursor               #ffffff
cursor_trail_color   #888888
selection_background #2b2b2b
selection_foreground #ffffff

# Cores do Terminal (Escala de Cinza Urbana)
# Black / Grey (Sombras e Carvão)
color0  #0f0f0f
color8  #2b2b2b

# Red (Cinza Médio Escuro)
color1  #555555
color9  #666666

# Green (Cinza Suave)
color2  #888888
color10 #a0a0a0

# Yellow / Gold (Cinza Prata)
color3  #b8b8b8
color11 #c5c5c5

# Blue (Cinza Claro Urbano)
color4  #d1d1d1
color12 #e0e0e0

# Magenta (Cinza Luminoso)
color5  #e0e0e0
color13 #ffffff

# Cyan (Cinza Asfalto / Metal)
color6  #888888
color14 #b8b8b8

# White (Branco Intenso da Cidade)
color7  #d1d1d1
color15 #ffffff

# Tab bar {{{
tab_bar_edge bottom
tab_bar_style powerline
active_tab_font_style bold

# --- Cores Harmonizadas (Noir City Escuro) ---
active_tab_foreground   #0f0f0f
active_tab_background   #ffffff
inactive_tab_foreground #888888
inactive_tab_background #1f1f1f
tab_bar_background      #0f0f0f
# ----------------------------------------------
