#Color scheme {{{

background_blur 1
background_opacity 0.85

# Initial D / Manga Noir (Carvão Profundo & Branco Fosco)
background           #000000
foreground           #d1d5db
cursor               #e2e8f0
cursor_trail_color   #8e96a0
selection_background #212429
selection_foreground #f8fafc

# Cores do Terminal (Grayscale de Alto Contraste)
# Black / Grey (Sombras e Carvão)
color0  #090a0b
color8  #34383f

# Red (Vermelho Frio/Grafite Escuro)
color1  #7c6266
color9  #99797e

# Green (Verde Musgo Grafite)
color2  #6e7f73
color10 #899e90

# Yellow / Gold (Areia/Papel Envelhecido)
color3  #a89a80
color11 #c9ba9d

# Blue (Aço/Chumbo)
color4  #5f7285
color12 #7a8fA3

# Magenta (Roxo Desbotado)
color5  #807086
color13 #9e8ba4

# Cyan (Cinza Mente/Asfalto)
color6  #6a8582
color14 #86A3a0

# White (Branco Fosco e Papel de Mangá)
color7  #d1d5db
color15 #f8fafc

# Tab bar {{{
tab_bar_edge bottom
tab_bar_style powerline
active_tab_font_style bold

# --- Cores Harmonizadas (Manga Noir Escuro) ---
active_tab_foreground   #090a0b
active_tab_background   #d1d5db
inactive_tab_foreground #8e96a0
inactive_tab_background #1a1c20
tab_bar_background      #090a0b
# ----------------------------------------------
