Color scheme {{{

background_blur 0

background_opacity 1.0

# Metropolis Ultra Dark Beige (No limite do bege sem te cegar)
background           #3b3630
foreground           #ebdccb
cursor               #cca67c
cursor_trail_color   #cca67c
selection_background #574f46
selection_foreground #fdf6ee

# Cores do Terminal
# Black / Grey
color0  #3b3630
color8  #6b6156

# Red
color1  #c4695c
color9  #db8274

# Green
color2  #7e8f75
color10 #98ab8f

# Yellow / Gold
color3  #cca360
color11 #e3b974

# Blue
color4  #6b8294
color12 #869fb3

# Magenta
color5  #997a8b
color13 #b393a5

# Cyan
color6  #849e9b
color14 #a0bebb

# White
color7  #ebdccb
color15 #fdf6ee

# Tab bar {{{
tab_bar_edge bottom
tab_bar_style powerline
active_tab_font_style bold

# --- Cores Harmonizadas com Metropolis Ultra Dark Beige ---
active_tab_foreground   #3b3630
active_tab_background   #cca67c
inactive_tab_foreground #ebdccb
inactive_tab_background #574f46
tab_bar_background      #3b3630
# ----------------------------------------------------------
