# Color scheme {{{

background_blur 1
background_opacity 0.85

# Sagittarius A* / Black Hole Palette
background           #08060a
foreground           #e1d2df
cursor               #ffea9f
cursor_trail_color   #e28d5c
selection_background #382435
selection_foreground #ffea9f

# Cores do Terminal (Espaço Profundo & Acreditações Radiantes)
# Black (Espaço / Sombras Cósmicas)
color0  #140f17
color8  #382435

# Red (Tons Quentes / Vermelho Cobre)
color1  #d14d41
color9  #e26356

# Green (Poeira Púrpura/Oliva Escuro)
color2  #70546d
color10 #8f6c8b

# Yellow / Gold (Brilho Incandescente do Anel)
color3  #e28d5c
color11 #ffea9f

# Blue (Anel de Fótons / Ciano Radiante)
color4  #5283c4
color12 #6ba4e8

# Magenta (Violeta do Disco de Acreção)
color5  #a3829e
color13 #c5757d

# Cyan (Azul Espectro Interno)
color6  #4892ad
color14 #64b3d1

# White (Luz Quente & Gasosa)
color7  #e1d2df
color15 #fff5d6

# Tab bar {{{
tab_bar_edge bottom
tab_bar_style powerline
active_tab_font_style bold

# --- Cores Harmonizadas (Black Hole Glow) ---
active_tab_foreground   #08060a
active_tab_background   #ffea9f
inactive_tab_foreground #a3829e
inactive_tab_background #140f17
tab_bar_background      #08060a
# ----------------------------------------------
