[main]
[main]
font=JetBrainsMono Nerd Font:size=18
dpi-aware=no
icon-theme=Papirus-Dark
prompt="󰍉 "
placeholder=""
width=40
tabs=4
horizontal-pad=20
vertical-pad=15
inner-pad=10
terminal=kitty

# Qual terminal ele deve usar para rodar apps de terminal (Como você tem o kitty)
terminal=kitty

[colors]
# Formato: RRGGBBAA (Vermelho, Verde, Azul, Alpha/Opacidade)
background=0b161ef0       # Céu noturno petróleo (com 94% de opacidade)
text=c9a876ff              # Dourado-areia das torres (texto normal)
match=7ee8ffff              # Ciano-claro — facho de luz no topo do arranha-céu
selection=3a5568ff          # Azul-acinzentado das sombras (fundo do item selecionado)
selection-text=7ee8ffff     # Texto selecionado em destaque
selection-match=a9e4dcff    # Match selecionado — brilho secundário quase branco-azulado
border=a9e4dcff              # Borda no tom do brilho secundário

[border]
width=2
radius=10

[dmenu]
mode=text
